# Generated by Django 4.2.7 on 2025-06-03 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NFT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("policy_id", models.CharField(max_length=1000, unique=True)),
                ("asset_id", models.CharField(max_length=1000, unique=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "NFT",
                "verbose_name_plural": "NFTs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="course",
            name="nft_id",
        ),
        migrations.AddField(
            model_name="course",
            name="nft",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.nft",
            ),
        ),
    ]
