# Generated by Django 4.2.7 on 2025-04-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variantitem",
            name="file",
            field=models.FileField(
                blank=True, default="", null=True, upload_to="course-file"
            ),
        ),
    ]
