# Generated by Django 4.2.7 on 2025-04-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="wallet_address",
            field=models.CharField(blank=True, max_length=1000, unique=True),
        ),
    ]
