# Generated by Django 4.2.7 on 2025-06-04 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_nft_remove_course_nft_id_course_nft"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="nft",
        ),
        migrations.AddField(
            model_name="nft",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nfts",
                to="api.course",
            ),
        ),
    ]
