# Generated by Django 4.2.7 on 2025-06-21 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_certificatenft'),
    ]

    operations = [
        migrations.DeleteModel(name='StudentQuizAnswer'),
        migrations.DeleteModel(name='StudentQuizAttempt'),
        migrations.DeleteModel(name='QuizOption'),
        migrations.DeleteModel(name='QuizQuestion'),
        migrations.DeleteModel(name='FinalQuiz'),
        migrations.DeleteModel(name='VariantQuiz'),
    ]
