# Generated by Django 4.2.7 on 2025-06-04 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_alter_nft_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nft',
            options={'ordering': ['-minted_at'], 'verbose_name': 'Course NFT', 'verbose_name_plural': 'Course NFTs'},
        ),
        migrations.RenameField(
            model_name='nft',
            old_name='created_at',
            new_name='minted_at',
        ),
        migrations.RemoveField(
            model_name='nft',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='nft',
            name='original_wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nfts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nft',
            name='asset_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nfts', to='api.course'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nft',
            name='policy_id',
            field=models.CharField(max_length=255),
        ),
    ]
