# Generated by Django 4.2.7 on 2025-02-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauths", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(max_length=100),
        ),
    ]
